version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend.dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend.dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
